services:
  python:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14.15-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: